#Requires -RunAsAdministrator
<#
  windows/Harden.ps1
  Run AFTER Install.ps1.

  1. Locks the hooks folder so only Administrators/SYSTEM can modify or
     delete it - malware running as your normal user cannot touch it.
  2. Installs a hidden SYSTEM scheduled task that runs at boot, at logon,
     and every 15 minutes: restores any missing hook file from a backup
     and re-applies core.hooksPath.

  Run as Administrator:
    .\Harden.ps1
#>

$ErrorActionPreference = 'Stop'

$root     = Split-Path -Parent $PSScriptRoot
$hooksDir = Join-Path $root "hooks"
$hooksDirGit = $hooksDir -replace '\\', '/'

Write-Host "=== Git Security Hooks - Windows Harden ===" -ForegroundColor Cyan

# --- 1. Pick a backup location on a different drive ------------------------
$rootDrive = (Get-Item $root).PSDrive.Name
$backupDir = $null

foreach ($d in (Get-PSDrive -PSProvider FileSystem | Where-Object { $_.Name -ne $rootDrive -and (Test-Path "$($_.Name):\") } | Sort-Object Name)) {
    $try = "$($d.Name):\GitHooksBackup"
    try {
        New-Item -ItemType Directory -Path $try -Force -ErrorAction Stop | Out-Null
        $backupDir = $try
        break
    } catch { continue }
}

if (-not $backupDir) {
    $backupDir = "C:\ProgramData\GitHooksBackup"
    New-Item -ItemType Directory -Path $backupDir -Force | Out-Null
}

Copy-Item -Path "$hooksDir\*" -Destination $backupDir -Recurse -Force
Write-Host "Backup: $backupDir" -ForegroundColor Green

# --- 2. Lock permissions ---------------------------------------------------
Write-Host "Applying NTFS lockdown..." -ForegroundColor Cyan
icacls $root /inheritance:r | Out-Null
icacls $root /grant:r "Administrators:(OI)(CI)F" | Out-Null
icacls $root /grant:r "SYSTEM:(OI)(CI)F" | Out-Null
icacls $root /grant:r "Users:(OI)(CI)RX" | Out-Null
icacls $root /grant:r "${env:USERDOMAIN}\${env:USERNAME}:(OI)(CI)RX" | Out-Null
Write-Host "Locked: only Administrators/SYSTEM can modify or delete." -ForegroundColor Green

# --- 3. Self-healing restore script ----------------------------------------
$restoreScript = Join-Path $root "restore-if-missing.ps1"

@"
# Auto-generated by windows\Harden.ps1 - do not edit by hand.
# Resolves its own location, so renaming or moving the folder does not break it.

`$root      = `$PSScriptRoot
`$hooksDir  = Join-Path `$root "hooks"
`$backupDir = "$backupDir"
`$required  = @("pre-commit","pre-merge-commit","pre-push","post-merge","post-checkout","post-rewrite","scanner.exe")

foreach (`$f in `$required) {
    `$target = Join-Path `$hooksDir `$f
    if (-not (Test-Path `$target)) {
        `$source = Join-Path `$backupDir `$f
        if (Test-Path `$source) { Copy-Item -Path `$source -Destination `$target -Force }
    }
}

git config --global core.hooksPath (`$hooksDir -replace '\\', '/')
"@ | Out-File -FilePath $restoreScript -Encoding utf8 -Force

# --- 4. Scheduled task -----------------------------------------------------
$taskName = "GitSecurityHooksGuard"

$action   = New-ScheduledTaskAction -Execute "powershell.exe" -Argument "-NoProfile -ExecutionPolicy Bypass -File `"$restoreScript`""
$tBoot    = New-ScheduledTaskTrigger -AtStartup
$tLogon   = New-ScheduledTaskTrigger -AtLogOn
$tRepeat  = New-ScheduledTaskTrigger -Once -At (Get-Date) -RepetitionInterval (New-TimeSpan -Minutes 15) -RepetitionDuration (New-TimeSpan -Days 3650)
$principal = New-ScheduledTaskPrincipal -UserId "SYSTEM" -LogonType ServiceAccount -RunLevel Highest
$settings  = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -Hidden -StartWhenAvailable

Unregister-ScheduledTask -TaskName $taskName -Confirm:$false -ErrorAction SilentlyContinue
Register-ScheduledTask -TaskName $taskName -Action $action -Trigger @($tBoot, $tLogon, $tRepeat) `
    -Principal $principal -Settings $settings `
    -Description "Restores git security hooks if missing and re-applies core.hooksPath. Runs as SYSTEM at boot, logon, and every 15 min." | Out-Null

Write-Host "Scheduled task '$taskName' installed (boot + logon + every 15 min, as SYSTEM)." -ForegroundColor Green

Write-Host ""
Write-Host "=== Hardening complete ===" -ForegroundColor Green
Write-Host "Restores from: $backupDir"
