#!/bin/sh
# unix/harden.sh
# Run AFTER install.sh, as root:  sudo ./harden.sh
#
# 1. Locks the folder to root ownership + immutable flag so a normal user
#    (and malware running as them) can't modify or delete the hooks.
# 2. Installs self-healing persistence: systemd timer on Linux, launchd
#    daemon on macOS - both run at boot and every 15 minutes.

set -e

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
HOOKS="$ROOT/hooks"
OS="$(uname -s)"
REAL_USER="${SUDO_USER:-$(whoami)}"
USER_HOME="$(eval echo ~"$REAL_USER")"
BACKUP="$USER_HOME/.git-hooks-backup"

if [ "$(id -u)" -ne 0 ]; then
    echo "Run with sudo:  sudo ./harden.sh"
    exit 1
fi

echo "=== Git Security Hooks - Unix Harden ($OS) ==="

# --- 1. Backup -------------------------------------------------------------
mkdir -p "$BACKUP"
cp -r "$HOOKS"/* "$BACKUP"/
chown -R "$REAL_USER" "$BACKUP"
echo "Backup: $BACKUP"

# --- 2. Lock permissions ---------------------------------------------------
chown -R root "$ROOT"
chmod -R 755 "$ROOT"
echo "Owned by root; normal user has read/execute only."

if [ "$OS" = "Linux" ] && command -v chattr >/dev/null 2>&1; then
    chattr +i "$HOOKS"/* 2>/dev/null && \
        echo "Immutable flag set (chattr +i). To edit later: sudo chattr -i $HOOKS/*" || \
        echo "chattr not supported on this filesystem - skipped."
elif [ "$OS" = "Darwin" ]; then
    chflags uchg "$HOOKS"/* 2>/dev/null && \
        echo "Immutable flag set (chflags uchg). To edit later: sudo chflags nouchg $HOOKS/*" || true
fi

# --- 3. Self-healing restore script ----------------------------------------
RESTORE="$ROOT/restore-if-missing.sh"
cat > "$RESTORE" <<EOF
#!/bin/sh
# Auto-generated by unix/harden.sh - do not edit by hand.
# Resolves its own location, so renaming or moving the folder does not break it.

SELF_DIR="\$(cd "\$(dirname "\$0")" && pwd)"
HOOKS="\$SELF_DIR/hooks"
BACKUP="$BACKUP"

for f in pre-commit pre-merge-commit pre-push post-merge post-checkout post-rewrite scanner; do
    if [ ! -f "\$HOOKS/\$f" ] && [ -f "\$BACKUP/\$f" ]; then
        cp "\$BACKUP/\$f" "\$HOOKS/\$f"
        chmod +x "\$HOOKS/\$f"
    fi
done

git config --global core.hooksPath "\$HOOKS"
EOF
chmod +x "$RESTORE"

# --- 4. Persistence --------------------------------------------------------
if [ "$OS" = "Linux" ] && command -v systemctl >/dev/null 2>&1; then

    cat > /etc/systemd/system/git-hooks-guard.service <<EOF
[Unit]
Description=Git Security Hooks Guard

[Service]
Type=oneshot
User=$REAL_USER
ExecStart=$RESTORE
EOF

    cat > /etc/systemd/system/git-hooks-guard.timer <<EOF
[Unit]
Description=Git Security Hooks Guard - boot + every 15 min

[Timer]
OnBootSec=1min
OnUnitActiveSec=15min
Persistent=true

[Install]
WantedBy=timers.target
EOF

    systemctl daemon-reload
    systemctl enable --now git-hooks-guard.timer
    echo "systemd timer installed (boot + every 15 min)."
    echo "Check with: systemctl status git-hooks-guard.timer"

elif [ "$OS" = "Darwin" ]; then

    PLIST="/Library/LaunchDaemons/com.gitsecurityhooks.guard.plist"
    cat > "$PLIST" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.gitsecurityhooks.guard</string>
    <key>ProgramArguments</key>
    <array><string>$RESTORE</string></array>
    <key>RunAtLoad</key>
    <true/>
    <key>StartInterval</key>
    <integer>900</integer>
</dict>
</plist>
EOF
    chown root:wheel "$PLIST"
    chmod 644 "$PLIST"
    launchctl load "$PLIST" 2>/dev/null || true
    echo "launchd daemon installed (boot + every 15 min)."
    echo "Check with: launchctl list | grep gitsecurityhooks"
fi

echo ""
echo "=== Hardening complete ==="
echo "Restores from: $BACKUP"
